services:
  db:
    image: postgres:16.11-alpine3.23
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio-server:
    image: minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=yassine_admin
      - MINIO_ROOT_PASSWORD=SuperSecretPassword123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  backend:
    build:
      context: ./backend
      network: host 
    container_name: 01blog-backend
    ports:
      - "8080:8080"
    environment:
      - MINIO_URL=http://minio-server:9000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/myapp
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret
    volumes:
      - ./backend:/app 
      - ~/.m2:/root/.m2 
    depends_on:
      - db
      - minio-server

  frontend:
    build:
      context: ./frontend
      network: host
    container_name: 01blog-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  db_data:
  minio_data: