spring.application.name=01blog
server.port=8080

# Connection Settings (Must match your docker-compose environment variables)
spring.datasource.url=jdbc:postgresql://localhost:5432/myapp
spring.datasource.username=admin
spring.datasource.password=secret

# Driver Configuration
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
# 'update' automatically creates/updates tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL in the console (useful for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect (Optional, usually auto-detected, but good to be explicit)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=c39RcF/nL73CD3SEe4LLs2yQCuXfjV6hk93EnvKayrc=
jwt.expiration=360000

