spring.application.name=01blog
spring.config.import=optional:file:../.env[.properties]
server.port=8080

# Connection Settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:myapp}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:360000}

# MinIO Settings
minio.url=${MINIO_URL:http://localhost:9000}
minio.public-url=${MINIO_PUBLIC_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=${MINIO_BUCKET_NAME:01blog-images}

# File Upload Settings
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Rate limiting
rate-limit.enabled=true
rate-limit.capacity=300
rate-limit.window-seconds=30
rate-limit.eviction-seconds=300
rate-limit.eviction-interval-ms=60000


