spring.application.name=01blog
server.port=8080

# Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/myapp
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=c39RcF/nL73CD3SEe4LLs2yQCuXfjV6hk93EnvKayrc=
jwt.expiration=360000

# MinIO Settings
minio.url=${MINIO_URL:http://localhost:9000}
minio.public-url=http://localhost:9000
minio.access-key=yassine_admin
minio.secret-key=SuperSecretPassword123
minio.bucket-name=01blog-images

# File Upload Settings
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


# docker exec minio-server sh -c "mc alias set myminio http://localhost:9000 yassine_admin SuperSecretPassword123 && mc mb myminio/01blog-images --ignore-existing && mc anonymous set download myminio/01blog-images"